@Api_HostAddress = https://localhost:32768

GET {{Api_HostAddress}}/ping/
Accept: application/json

###

GET {{Api_HostAddress}}/healthcheck/
Accept: application/json

###

POST {{Api_HostAddress}}/driver/
Accept: application/json
Content-Type: application/json

{
  "fullName":"driver one"
}
###
