CREATE TABLE [Driver]
(
	[Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] VARCHAR(50) NOT NULL, 
    [AddressLine1] VARCHAR(50) NOT NULL, 
    [AddressLine2] VARCHAR(50) NOT NULL,
    [PhoneNumber] VARCHAR(50) NOT NULL
)
